[package]
name = "uncrustable"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "2.0.1", features = ["full"] }
internment = "0.8.6"
logos = "0.15.0"
pest = "2.7.15"
pest_derive = "2.7.15"
